In [1]:
import pandas as pd
import numpy as np
import re
from scipy.spatial.distance import cosine

In [2]:
with open('sentences.txt', 'r') as f:
    text = f.read();  
source_text = text.split('.\n')
source_text = [elem.lower() for elem in source_text]

In [3]:
all_word = []
sentences = []
for sentence in source_text:
    words_source = re.split('[^a-z]', sentence)
    words = [word for word in words_source if word != '']
    all_word.extend(words)
    sentences.append(words)
all_word = set(all_word)

In [4]:
words = []
for sentence in sentences:
    list1 = []
    for word in all_word:
        list1.append(sentence.count(word))
    words.append(list1)

In [5]:
df = pd.DataFrame(data=words, columns=all_word)
df.head()

,major,such,simply,apple,running,upgrade,domestic,learned,releasing,for,...,between,starting,offered,have,frequency,purchase,version,comparison,vermin,some
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [6]:
base = df.iloc[[0]]

In [7]:
df['cosine'] = df.apply(lambda x: cosine(base, x), axis=1)
df.head()

,major,such,simply,apple,running,upgrade,domestic,learned,releasing,for,...,starting,offered,have,frequency,purchase,version,comparison,vermin,some,cosine
0,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0.000000
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.952754
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0.864474
3,0,1,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0.895172
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0.777089

In [8]:
df.sort_values(by=["cosine"])

,major,such,simply,apple,running,upgrade,domestic,learned,releasing,for,...,starting,offered,have,frequency,purchase,version,comparison,vermin,some,cosine
0,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0.000000
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0.732739
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0.777089
21,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.825036
10,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0.832817
12,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.839643
16,0,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.840636
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.842757
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0.864474
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.870359
14,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.874012
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.880477
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.884272
19,0,0,0,1,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0.888544
3,0,1,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0.895172
9,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0.905509
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.925875
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.940239
15,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0.944272
18,0,0,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0.944272
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.952754
17,0,0,0,1,0,0,0,0,1,1,...,0,0,0,0,1,0,0,0,0,0.956645

In [9]:
with open('submission-1.txt', 'w') as file:
    file.write(f'{" ".join(map(str,list(df.sort_values(by=["cosine"])[1:3].index)))}\n')